### ISSUE TITLE
Event/Login does not properly show logged in character

### ISSUE THREAD

**Issue by NotNite** [Xpahtalo/Ffxiv2Mqtt#1]
`ffxiv/Event/Login {"LoggedIn":true,"LoggedInCharacter":""}`

Also goes for when logging out.

**Comment by Xpahtalo** [comment]
[Fixed](https://github.com/Xpahtalo/Ffxiv2Mqtt/commit/9415d84d92fbd6b0999a2272a3dfc38250f6174f). I also renamed "LoggedInCharacter" to "Character", as the name will stay in the payload when logging out. I'll push this change and a few other bugfixes sometime tonight.
