### ISSUE TITLE
Option to remove topic display for topic subscriptions

### ISSUE THREAD

**Issue by graytonio** [Xpahtalo/Ffxiv2Mqtt#11]
An option where I could disable showing the topic name when doing toasts/chat boxes for topic subscriptions.

![image](https://user-images.githubusercontent.com/9275515/188337051-0b69b00c-9475-4385-a52e-ffa382bcd95e.png)

![image](https://user-images.githubusercontent.com/9275515/188337057-b751d50f-5892-4d22-88c3-22be44059891.png)

**Comment by Xpahtalo** [comment]
I'll add that to the next release. Hopefully this week.
