### ISSUE TITLE
BRD gauge triggering DNC gauge updates to be sent/No DNC gauge updates

### ISSUE THREAD

**Issue by LucasTheDrgn** [Xpahtalo/Ffxiv2Mqtt#12]
Steps to reproduce:

1. `mosquitto_sub -v -t "ffxiv/Player/JobGauge/DNC" -q 2`
2. Change class to BRD
3. Begin a song 
4. Each frame, a DNC gauge update is sent with out of range values corresponding to BRD gauge values
5. Reset emnity, change class to DNC
6. Begin/complete a dance, gain esprit, and/or gain fourfold feathers stacks
7. No gauge update is sent

Plugin version v1.0.3.6

**Comment by Xpahtalo** [comment]
I've pushed a fix. It should show up some time tomorrow.
