### ISSUE TITLE
Just wondering if an update for Dawntrail is expected

### ISSUE THREAD

**Issue by Krojack** [Xpahtalo/Ffxiv2Mqtt#15]
Just curious if an update is expected. If yes but real life still busy than take your time, I'll wait. If no update is expected then I know I can remove the plugin and look for something else is all.

**Comment by Xpahtalo** [comment]
Yep, in a couple weeks. It was delayed due to some stuff it uses being very broken, and now I'm traveling for work, so I can't push an update until I am back.
