### ISSUE TITLE
No way to see current status effects

### ISSUE THREAD

**Issue by NotNite** [Xpahtalo/Ffxiv2Mqtt#5]
I wanna display on my LED matrix when I have my stance on :(

**Comment by Xpahtalo** [comment]
Tentatively worked out a solution. It might not stay in it's current form.

**Comment by Xpahtalo** [comment]
Finished in [47586d3](https://github.com/Xpahtalo/Ffxiv2Mqtt/commit/47586d3b691a5f23a60b05a5327c16dad5b5aed9)
