### ISSUE TITLE
Player/Info does not update when stats change

### ISSUE THREAD

**Issue by NotNite** [Xpahtalo/Ffxiv2Mqtt#6]
Steps to repro:
- `mosquitto_sub -h 127.0.0.1 -v -t "ffxiv/#" -u julian -P "my_cool_password"`
- Change jobs and witness Player/Info fire
- Take off gear piece to change max HP (I presume this also happens when levelling up, but that's hard to test, LMAO)
- Notice it does not fire again

**Comment by Xpahtalo** [comment]
Is this with v1.0.1.0? I'm seeing the message when I unequip and re-equip an accessory.
![image](https://user-images.githubusercontent.com/106037495/176235348-f1e2e0f7-a8bd-41c2-8df6-434a5c3c6959.png)

**Comment by NotNite** [comment]
Yes, this is with 1.0.1.0.

**Comment by Xpahtalo** [comment]
Just as a sanity check to make sure before I dig into it more, can you try with `-q 2`?

**Comment by NotNite** [comment]
I might be going insane now it works. Weird!
